//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asistencia()
        {
            this.AuditoriaAsistencia = new HashSet<AuditoriaAsistencia>();
        }
    
        public int ID_Asistencia { get; set; }
        public int ID_Estudiante { get; set; }
        public Nullable<System.DateTime> Fecha_Asistencia { get; set; }
        public int ID_Estado { get; set; }
        public int ID_Clase { get; set; }
        public bool Activo { get; set; }
    
        public virtual Clases Clases { get; set; }
        public virtual Estudiantes Estudiantes { get; set; }
        public virtual EstadosAsistencia EstadosAsistencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditoriaAsistencia> AuditoriaAsistencia { get; set; }
    }
}
