//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Calificaciones()
        {
            this.AuditoriaCalificaciones = new HashSet<AuditoriaCalificaciones>();
        }
    
        public int ID_Calificacion { get; set; }
        public int ID_Estudiante { get; set; }
        public decimal Calificacion { get; set; }
        public System.DateTime FechaCalificacion { get; set; }
        public int ID_Clase { get; set; }
        public int ID_Usuario { get; set; }
        public int ID_TipoEvaluacion { get; set; }
        public decimal PorcentajeTotal { get; set; }
        public bool Activo { get; set; }
        public string Retroalimentacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditoriaCalificaciones> AuditoriaCalificaciones { get; set; }
        public virtual Estudiantes Estudiantes { get; set; }
        public virtual TiposEvaluaciones TiposEvaluaciones { get; set; }
    }
}
