//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuraciones
    {
        public int ID_Configuracion { get; set; }
        public bool Notificaciones { get; set; }
        public bool Recordatorios { get; set; }
        public string Apariencia { get; set; }
        public string PoliticaContrasenas { get; set; }
    }
}
