//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocentesClases
    {
        public int ID_DocenteClase { get; set; }
        public int ID_Docente { get; set; }
        public int ID_Clase { get; set; }
    
        public virtual Clases Clases { get; set; }
        public virtual Docentes Docentes { get; set; }
    }
}
