//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstudiantesPadres
    {
        public int ID_EstudiantePadre { get; set; }
        public int ID_Estudiante { get; set; }
        public int ID_Padre { get; set; }
    
        public virtual Estudiantes Estudiantes { get; set; }
        public virtual Padres Padres { get; set; }
    }
}
