//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensajeria
    {
        public int ID_Mensaje { get; set; }
        public string Contenido { get; set; }
        public System.DateTime Fecha_Envio { get; set; }
        public int Remitente_ID { get; set; }
        public int Destinatario_ID { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
    }
}
