//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CIDEPEntities : DbContext
    {
        public CIDEPEntities()
            : base("name=CIDEPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asistencia> Asistencia { get; set; }
        public virtual DbSet<AuditoriaAdministracion> AuditoriaAdministracion { get; set; }
        public virtual DbSet<AuditoriaAsistencia> AuditoriaAsistencia { get; set; }
        public virtual DbSet<AuditoriaAvisosGenerales> AuditoriaAvisosGenerales { get; set; }
        public virtual DbSet<AuditoriaCalificaciones> AuditoriaCalificaciones { get; set; }
        public virtual DbSet<AuditoriaClases> AuditoriaClases { get; set; }
        public virtual DbSet<AuditoriaDocentes> AuditoriaDocentes { get; set; }
        public virtual DbSet<AuditoriaEstudiantes> AuditoriaEstudiantes { get; set; }
        public virtual DbSet<AuditoriaIniciosSesion> AuditoriaIniciosSesion { get; set; }
        public virtual DbSet<AvisosGenerales> AvisosGenerales { get; set; }
        public virtual DbSet<Calificaciones> Calificaciones { get; set; }
        public virtual DbSet<Clases> Clases { get; set; }
        public virtual DbSet<Configuraciones> Configuraciones { get; set; }
        public virtual DbSet<Cursos> Cursos { get; set; }
        public virtual DbSet<Docentes> Docentes { get; set; }
        public virtual DbSet<DocentesClases> DocentesClases { get; set; }
        public virtual DbSet<EstadosAsistencia> EstadosAsistencia { get; set; }
        public virtual DbSet<Estudiantes> Estudiantes { get; set; }
        public virtual DbSet<EstudiantesGrados> EstudiantesGrados { get; set; }
        public virtual DbSet<EstudiantesPadres> EstudiantesPadres { get; set; }
        public virtual DbSet<Grados> Grados { get; set; }
        public virtual DbSet<IniciosSesion> IniciosSesion { get; set; }
        public virtual DbSet<Mensajeria> Mensajeria { get; set; }
        public virtual DbSet<Padres> Padres { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<TiposEvaluaciones> TiposEvaluaciones { get; set; }
        public virtual DbSet<Tokens> Tokens { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<ArchivosCSV> ArchivosCSV { get; set; }
    
        public virtual int BorrarAsistencia(Nullable<int> iD_Asistencia, Nullable<int> rolUsuario, Nullable<int> iD_Usuario)
        {
            var iD_AsistenciaParameter = iD_Asistencia.HasValue ?
                new ObjectParameter("ID_Asistencia", iD_Asistencia) :
                new ObjectParameter("ID_Asistencia", typeof(int));
    
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            var iD_UsuarioParameter = iD_Usuario.HasValue ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BorrarAsistencia", iD_AsistenciaParameter, rolUsuarioParameter, iD_UsuarioParameter);
        }
    
        public virtual int BorrarAvisoGeneral(Nullable<int> iD_AvisoGeneral, Nullable<int> rolUsuario, Nullable<int> iD_Usuario)
        {
            var iD_AvisoGeneralParameter = iD_AvisoGeneral.HasValue ?
                new ObjectParameter("ID_AvisoGeneral", iD_AvisoGeneral) :
                new ObjectParameter("ID_AvisoGeneral", typeof(int));
    
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            var iD_UsuarioParameter = iD_Usuario.HasValue ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BorrarAvisoGeneral", iD_AvisoGeneralParameter, rolUsuarioParameter, iD_UsuarioParameter);
        }
    
        public virtual int BorrarCalificacion(Nullable<int> iD_Calificacion, Nullable<int> iD_Usuario)
        {
            var iD_CalificacionParameter = iD_Calificacion.HasValue ?
                new ObjectParameter("ID_Calificacion", iD_Calificacion) :
                new ObjectParameter("ID_Calificacion", typeof(int));
    
            var iD_UsuarioParameter = iD_Usuario.HasValue ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BorrarCalificacion", iD_CalificacionParameter, iD_UsuarioParameter);
        }
    
        public virtual int BorrarClase(Nullable<int> iD_Clase, Nullable<int> rolUsuario, Nullable<int> iD_Usuario)
        {
            var iD_ClaseParameter = iD_Clase.HasValue ?
                new ObjectParameter("ID_Clase", iD_Clase) :
                new ObjectParameter("ID_Clase", typeof(int));
    
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            var iD_UsuarioParameter = iD_Usuario.HasValue ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BorrarClase", iD_ClaseParameter, rolUsuarioParameter, iD_UsuarioParameter);
        }
    
        public virtual int BorrarDocente(Nullable<int> iD_Docente, Nullable<int> rolUsuario, Nullable<int> iD_UsuarioQueElimina)
        {
            var iD_DocenteParameter = iD_Docente.HasValue ?
                new ObjectParameter("ID_Docente", iD_Docente) :
                new ObjectParameter("ID_Docente", typeof(int));
    
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            var iD_UsuarioQueEliminaParameter = iD_UsuarioQueElimina.HasValue ?
                new ObjectParameter("ID_UsuarioQueElimina", iD_UsuarioQueElimina) :
                new ObjectParameter("ID_UsuarioQueElimina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BorrarDocente", iD_DocenteParameter, rolUsuarioParameter, iD_UsuarioQueEliminaParameter);
        }
    
        public virtual int BorrarEstadoAsistencia(Nullable<int> iD_Estado, Nullable<int> rolUsuario, Nullable<int> iD_Usuario)
        {
            var iD_EstadoParameter = iD_Estado.HasValue ?
                new ObjectParameter("ID_Estado", iD_Estado) :
                new ObjectParameter("ID_Estado", typeof(int));
    
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            var iD_UsuarioParameter = iD_Usuario.HasValue ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BorrarEstadoAsistencia", iD_EstadoParameter, rolUsuarioParameter, iD_UsuarioParameter);
        }
    
        public virtual int BorrarEstudiante(Nullable<int> iD_Estudiante, Nullable<int> rolUsuario, Nullable<int> iD_UsuarioQueElimina)
        {
            var iD_EstudianteParameter = iD_Estudiante.HasValue ?
                new ObjectParameter("ID_Estudiante", iD_Estudiante) :
                new ObjectParameter("ID_Estudiante", typeof(int));
    
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            var iD_UsuarioQueEliminaParameter = iD_UsuarioQueElimina.HasValue ?
                new ObjectParameter("ID_UsuarioQueElimina", iD_UsuarioQueElimina) :
                new ObjectParameter("ID_UsuarioQueElimina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BorrarEstudiante", iD_EstudianteParameter, rolUsuarioParameter, iD_UsuarioQueEliminaParameter);
        }
    
        public virtual int BorrarUsuario(Nullable<int> iD_Usuario, Nullable<int> rolUsuario, Nullable<int> iD_UsuarioQueElimina)
        {
            var iD_UsuarioParameter = iD_Usuario.HasValue ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(int));
    
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            var iD_UsuarioQueEliminaParameter = iD_UsuarioQueElimina.HasValue ?
                new ObjectParameter("ID_UsuarioQueElimina", iD_UsuarioQueElimina) :
                new ObjectParameter("ID_UsuarioQueElimina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BorrarUsuario", iD_UsuarioParameter, rolUsuarioParameter, iD_UsuarioQueEliminaParameter);
        }
    
        public virtual ObjectResult<BuscarInformacionUsuario_Result> BuscarInformacionUsuario(Nullable<int> iD_Usuario)
        {
            var iD_UsuarioParameter = iD_Usuario.HasValue ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BuscarInformacionUsuario_Result>("BuscarInformacionUsuario", iD_UsuarioParameter);
        }
    
        public virtual ObjectResult<string> CambiarContrasenna(Nullable<int> iD_Usuario, string contrasennaActual, string nuevaContrasenna)
        {
            var iD_UsuarioParameter = iD_Usuario.HasValue ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(int));
    
            var contrasennaActualParameter = contrasennaActual != null ?
                new ObjectParameter("ContrasennaActual", contrasennaActual) :
                new ObjectParameter("ContrasennaActual", typeof(string));
    
            var nuevaContrasennaParameter = nuevaContrasenna != null ?
                new ObjectParameter("NuevaContrasenna", nuevaContrasenna) :
                new ObjectParameter("NuevaContrasenna", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("CambiarContrasenna", iD_UsuarioParameter, contrasennaActualParameter, nuevaContrasennaParameter);
        }
    
        public virtual int CrearAsistencia(Nullable<int> iD_Estudiante, Nullable<int> iD_Estado, Nullable<int> iD_Clase, Nullable<System.DateTime> fecha_Asistencia, Nullable<int> iD_Usuario)
        {
            var iD_EstudianteParameter = iD_Estudiante.HasValue ?
                new ObjectParameter("ID_Estudiante", iD_Estudiante) :
                new ObjectParameter("ID_Estudiante", typeof(int));
    
            var iD_EstadoParameter = iD_Estado.HasValue ?
                new ObjectParameter("ID_Estado", iD_Estado) :
                new ObjectParameter("ID_Estado", typeof(int));
    
            var iD_ClaseParameter = iD_Clase.HasValue ?
                new ObjectParameter("ID_Clase", iD_Clase) :
                new ObjectParameter("ID_Clase", typeof(int));
    
            var fecha_AsistenciaParameter = fecha_Asistencia.HasValue ?
                new ObjectParameter("Fecha_Asistencia", fecha_Asistencia) :
                new ObjectParameter("Fecha_Asistencia", typeof(System.DateTime));
    
            var iD_UsuarioParameter = iD_Usuario.HasValue ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CrearAsistencia", iD_EstudianteParameter, iD_EstadoParameter, iD_ClaseParameter, fecha_AsistenciaParameter, iD_UsuarioParameter);
        }
    
        public virtual int CrearAvisoGeneral(string mensaje, Nullable<int> iD_Usuario)
        {
            var mensajeParameter = mensaje != null ?
                new ObjectParameter("Mensaje", mensaje) :
                new ObjectParameter("Mensaje", typeof(string));
    
            var iD_UsuarioParameter = iD_Usuario.HasValue ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CrearAvisoGeneral", mensajeParameter, iD_UsuarioParameter);
        }
    
        public virtual int CrearCalificacion(Nullable<int> iD_Estudiante, Nullable<int> iD_Clase, Nullable<decimal> calificacion, Nullable<int> iD_TipoEvaluacion, Nullable<int> iD_Usuario, Nullable<decimal> porcentaje, string retroalimentacion)
        {
            var iD_EstudianteParameter = iD_Estudiante.HasValue ?
                new ObjectParameter("ID_Estudiante", iD_Estudiante) :
                new ObjectParameter("ID_Estudiante", typeof(int));
    
            var iD_ClaseParameter = iD_Clase.HasValue ?
                new ObjectParameter("ID_Clase", iD_Clase) :
                new ObjectParameter("ID_Clase", typeof(int));
    
            var calificacionParameter = calificacion.HasValue ?
                new ObjectParameter("Calificacion", calificacion) :
                new ObjectParameter("Calificacion", typeof(decimal));
    
            var iD_TipoEvaluacionParameter = iD_TipoEvaluacion.HasValue ?
                new ObjectParameter("ID_TipoEvaluacion", iD_TipoEvaluacion) :
                new ObjectParameter("ID_TipoEvaluacion", typeof(int));
    
            var iD_UsuarioParameter = iD_Usuario.HasValue ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(int));
    
            var porcentajeParameter = porcentaje.HasValue ?
                new ObjectParameter("Porcentaje", porcentaje) :
                new ObjectParameter("Porcentaje", typeof(decimal));
    
            var retroalimentacionParameter = retroalimentacion != null ?
                new ObjectParameter("Retroalimentacion", retroalimentacion) :
                new ObjectParameter("Retroalimentacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CrearCalificacion", iD_EstudianteParameter, iD_ClaseParameter, calificacionParameter, iD_TipoEvaluacionParameter, iD_UsuarioParameter, porcentajeParameter, retroalimentacionParameter);
        }
    
        public virtual int CrearClase(Nullable<int> iD_Curso, Nullable<int> iD_Grado, Nullable<int> iD_Usuario, Nullable<int> rolUsuario)
        {
            var iD_CursoParameter = iD_Curso.HasValue ?
                new ObjectParameter("ID_Curso", iD_Curso) :
                new ObjectParameter("ID_Curso", typeof(int));
    
            var iD_GradoParameter = iD_Grado.HasValue ?
                new ObjectParameter("ID_Grado", iD_Grado) :
                new ObjectParameter("ID_Grado", typeof(int));
    
            var iD_UsuarioParameter = iD_Usuario.HasValue ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(int));
    
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CrearClase", iD_CursoParameter, iD_GradoParameter, iD_UsuarioParameter, rolUsuarioParameter);
        }
    
        public virtual int CrearCurso(string nombreCurso, Nullable<int> rolUsuario, Nullable<int> iD_Usuario)
        {
            var nombreCursoParameter = nombreCurso != null ?
                new ObjectParameter("NombreCurso", nombreCurso) :
                new ObjectParameter("NombreCurso", typeof(string));
    
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            var iD_UsuarioParameter = iD_Usuario.HasValue ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CrearCurso", nombreCursoParameter, rolUsuarioParameter, iD_UsuarioParameter);
        }
    
        public virtual int CrearDocente(string cedula, string nombre, string primerApellido, string segundoApellido, Nullable<System.DateTime> fechaNacimiento, Nullable<int> iD_Usuario, Nullable<int> rolUsuario, Nullable<int> iD_UsuarioQueInserta)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var primerApellidoParameter = primerApellido != null ?
                new ObjectParameter("PrimerApellido", primerApellido) :
                new ObjectParameter("PrimerApellido", typeof(string));
    
            var segundoApellidoParameter = segundoApellido != null ?
                new ObjectParameter("SegundoApellido", segundoApellido) :
                new ObjectParameter("SegundoApellido", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(System.DateTime));
    
            var iD_UsuarioParameter = iD_Usuario.HasValue ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(int));
    
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            var iD_UsuarioQueInsertaParameter = iD_UsuarioQueInserta.HasValue ?
                new ObjectParameter("ID_UsuarioQueInserta", iD_UsuarioQueInserta) :
                new ObjectParameter("ID_UsuarioQueInserta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CrearDocente", cedulaParameter, nombreParameter, primerApellidoParameter, segundoApellidoParameter, fechaNacimientoParameter, iD_UsuarioParameter, rolUsuarioParameter, iD_UsuarioQueInsertaParameter);
        }
    
        public virtual int CrearEstadoAsistencia(string nombreEstado, Nullable<int> iD_Usuario, Nullable<int> rolUsuario)
        {
            var nombreEstadoParameter = nombreEstado != null ?
                new ObjectParameter("NombreEstado", nombreEstado) :
                new ObjectParameter("NombreEstado", typeof(string));
    
            var iD_UsuarioParameter = iD_Usuario.HasValue ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(int));
    
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CrearEstadoAsistencia", nombreEstadoParameter, iD_UsuarioParameter, rolUsuarioParameter);
        }
    
        public virtual int CrearEstudiante(string cedula, string nombre, string primerApellido, string segundoApellido, Nullable<System.DateTime> fechaNacimiento, Nullable<int> iD_Usuario, Nullable<int> rolUsuario, Nullable<int> iD_UsuarioQueInserta)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var primerApellidoParameter = primerApellido != null ?
                new ObjectParameter("PrimerApellido", primerApellido) :
                new ObjectParameter("PrimerApellido", typeof(string));
    
            var segundoApellidoParameter = segundoApellido != null ?
                new ObjectParameter("SegundoApellido", segundoApellido) :
                new ObjectParameter("SegundoApellido", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(System.DateTime));
    
            var iD_UsuarioParameter = iD_Usuario.HasValue ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(int));
    
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            var iD_UsuarioQueInsertaParameter = iD_UsuarioQueInserta.HasValue ?
                new ObjectParameter("ID_UsuarioQueInserta", iD_UsuarioQueInserta) :
                new ObjectParameter("ID_UsuarioQueInserta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CrearEstudiante", cedulaParameter, nombreParameter, primerApellidoParameter, segundoApellidoParameter, fechaNacimientoParameter, iD_UsuarioParameter, rolUsuarioParameter, iD_UsuarioQueInsertaParameter);
        }
    
        public virtual int CrearGrado(string nombreGrado, Nullable<int> rolUsuario)
        {
            var nombreGradoParameter = nombreGrado != null ?
                new ObjectParameter("NombreGrado", nombreGrado) :
                new ObjectParameter("NombreGrado", typeof(string));
    
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CrearGrado", nombreGradoParameter, rolUsuarioParameter);
        }
    
        public virtual int CrearPadre(string nombre, string primerApellido, string segundoApellido, string email, string numero, Nullable<int> rolUsuario, Nullable<int> iD_UsuarioQueInserta)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var primerApellidoParameter = primerApellido != null ?
                new ObjectParameter("PrimerApellido", primerApellido) :
                new ObjectParameter("PrimerApellido", typeof(string));
    
            var segundoApellidoParameter = segundoApellido != null ?
                new ObjectParameter("SegundoApellido", segundoApellido) :
                new ObjectParameter("SegundoApellido", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var numeroParameter = numero != null ?
                new ObjectParameter("Numero", numero) :
                new ObjectParameter("Numero", typeof(string));
    
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            var iD_UsuarioQueInsertaParameter = iD_UsuarioQueInserta.HasValue ?
                new ObjectParameter("ID_UsuarioQueInserta", iD_UsuarioQueInserta) :
                new ObjectParameter("ID_UsuarioQueInserta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CrearPadre", nombreParameter, primerApellidoParameter, segundoApellidoParameter, emailParameter, numeroParameter, rolUsuarioParameter, iD_UsuarioQueInsertaParameter);
        }
    
        public virtual int CrearTipoEvaluacion(string descripcion, Nullable<int> rolUsuario)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CrearTipoEvaluacion", descripcionParameter, rolUsuarioParameter);
        }
    
        public virtual int CrearUsuario(string nombre_Usuario, Nullable<int> iD_RolUsuarioNuevo, string email, Nullable<int> iD_Rol, Nullable<int> iD_Usuario)
        {
            var nombre_UsuarioParameter = nombre_Usuario != null ?
                new ObjectParameter("Nombre_Usuario", nombre_Usuario) :
                new ObjectParameter("Nombre_Usuario", typeof(string));
    
            var iD_RolUsuarioNuevoParameter = iD_RolUsuarioNuevo.HasValue ?
                new ObjectParameter("ID_RolUsuarioNuevo", iD_RolUsuarioNuevo) :
                new ObjectParameter("ID_RolUsuarioNuevo", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var iD_RolParameter = iD_Rol.HasValue ?
                new ObjectParameter("ID_Rol", iD_Rol) :
                new ObjectParameter("ID_Rol", typeof(int));
    
            var iD_UsuarioParameter = iD_Usuario.HasValue ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CrearUsuario", nombre_UsuarioParameter, iD_RolUsuarioNuevoParameter, emailParameter, iD_RolParameter, iD_UsuarioParameter);
        }
    
        public virtual int CrearUsuarioAdmin(string nombre_Usuario, string contrasenna, Nullable<int> iD_RolUsuarioNuevo, string email, Nullable<int> iD_Rol)
        {
            var nombre_UsuarioParameter = nombre_Usuario != null ?
                new ObjectParameter("Nombre_Usuario", nombre_Usuario) :
                new ObjectParameter("Nombre_Usuario", typeof(string));
    
            var contrasennaParameter = contrasenna != null ?
                new ObjectParameter("Contrasenna", contrasenna) :
                new ObjectParameter("Contrasenna", typeof(string));
    
            var iD_RolUsuarioNuevoParameter = iD_RolUsuarioNuevo.HasValue ?
                new ObjectParameter("ID_RolUsuarioNuevo", iD_RolUsuarioNuevo) :
                new ObjectParameter("ID_RolUsuarioNuevo", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var iD_RolParameter = iD_Rol.HasValue ?
                new ObjectParameter("ID_Rol", iD_Rol) :
                new ObjectParameter("ID_Rol", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CrearUsuarioAdmin", nombre_UsuarioParameter, contrasennaParameter, iD_RolUsuarioNuevoParameter, emailParameter, iD_RolParameter);
        }
    
        public virtual int EditarAsistencia(Nullable<int> iD_Asistencia, Nullable<int> iD_Estudiante, Nullable<int> iD_Estado, Nullable<int> iD_Usuario)
        {
            var iD_AsistenciaParameter = iD_Asistencia.HasValue ?
                new ObjectParameter("ID_Asistencia", iD_Asistencia) :
                new ObjectParameter("ID_Asistencia", typeof(int));
    
            var iD_EstudianteParameter = iD_Estudiante.HasValue ?
                new ObjectParameter("ID_Estudiante", iD_Estudiante) :
                new ObjectParameter("ID_Estudiante", typeof(int));
    
            var iD_EstadoParameter = iD_Estado.HasValue ?
                new ObjectParameter("ID_Estado", iD_Estado) :
                new ObjectParameter("ID_Estado", typeof(int));
    
            var iD_UsuarioParameter = iD_Usuario.HasValue ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditarAsistencia", iD_AsistenciaParameter, iD_EstudianteParameter, iD_EstadoParameter, iD_UsuarioParameter);
        }
    
        public virtual int EditarAvisoGeneral(Nullable<int> iD_AvisoGeneral, string mensaje, Nullable<int> iD_Usuario)
        {
            var iD_AvisoGeneralParameter = iD_AvisoGeneral.HasValue ?
                new ObjectParameter("ID_AvisoGeneral", iD_AvisoGeneral) :
                new ObjectParameter("ID_AvisoGeneral", typeof(int));
    
            var mensajeParameter = mensaje != null ?
                new ObjectParameter("Mensaje", mensaje) :
                new ObjectParameter("Mensaje", typeof(string));
    
            var iD_UsuarioParameter = iD_Usuario.HasValue ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditarAvisoGeneral", iD_AvisoGeneralParameter, mensajeParameter, iD_UsuarioParameter);
        }
    
        public virtual int EditarCalificacion(Nullable<int> iD_Calificacion, Nullable<int> iD_Estudiante, Nullable<int> iD_Clase, Nullable<decimal> calificacion, Nullable<int> iD_TipoEvaluacion, Nullable<int> iD_Usuario, Nullable<decimal> porcentaje, string retroalimentacion)
        {
            var iD_CalificacionParameter = iD_Calificacion.HasValue ?
                new ObjectParameter("ID_Calificacion", iD_Calificacion) :
                new ObjectParameter("ID_Calificacion", typeof(int));
    
            var iD_EstudianteParameter = iD_Estudiante.HasValue ?
                new ObjectParameter("ID_Estudiante", iD_Estudiante) :
                new ObjectParameter("ID_Estudiante", typeof(int));
    
            var iD_ClaseParameter = iD_Clase.HasValue ?
                new ObjectParameter("ID_Clase", iD_Clase) :
                new ObjectParameter("ID_Clase", typeof(int));
    
            var calificacionParameter = calificacion.HasValue ?
                new ObjectParameter("Calificacion", calificacion) :
                new ObjectParameter("Calificacion", typeof(decimal));
    
            var iD_TipoEvaluacionParameter = iD_TipoEvaluacion.HasValue ?
                new ObjectParameter("ID_TipoEvaluacion", iD_TipoEvaluacion) :
                new ObjectParameter("ID_TipoEvaluacion", typeof(int));
    
            var iD_UsuarioParameter = iD_Usuario.HasValue ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(int));
    
            var porcentajeParameter = porcentaje.HasValue ?
                new ObjectParameter("Porcentaje", porcentaje) :
                new ObjectParameter("Porcentaje", typeof(decimal));
    
            var retroalimentacionParameter = retroalimentacion != null ?
                new ObjectParameter("Retroalimentacion", retroalimentacion) :
                new ObjectParameter("Retroalimentacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditarCalificacion", iD_CalificacionParameter, iD_EstudianteParameter, iD_ClaseParameter, calificacionParameter, iD_TipoEvaluacionParameter, iD_UsuarioParameter, porcentajeParameter, retroalimentacionParameter);
        }
    
        public virtual int EditarClase(Nullable<int> iD_Clase, Nullable<int> iD_Curso, Nullable<int> iD_Grado, Nullable<int> iD_Usuario, Nullable<int> rolUsuario, Nullable<bool> activo)
        {
            var iD_ClaseParameter = iD_Clase.HasValue ?
                new ObjectParameter("ID_Clase", iD_Clase) :
                new ObjectParameter("ID_Clase", typeof(int));
    
            var iD_CursoParameter = iD_Curso.HasValue ?
                new ObjectParameter("ID_Curso", iD_Curso) :
                new ObjectParameter("ID_Curso", typeof(int));
    
            var iD_GradoParameter = iD_Grado.HasValue ?
                new ObjectParameter("ID_Grado", iD_Grado) :
                new ObjectParameter("ID_Grado", typeof(int));
    
            var iD_UsuarioParameter = iD_Usuario.HasValue ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(int));
    
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditarClase", iD_ClaseParameter, iD_CursoParameter, iD_GradoParameter, iD_UsuarioParameter, rolUsuarioParameter, activoParameter);
        }
    
        public virtual int EditarDocente(Nullable<int> iD_Docente, string cedula, string nombre, string primerApellido, string segundoApellido, Nullable<System.DateTime> fechaNacimiento, Nullable<int> rolUsuario, Nullable<bool> activo, Nullable<int> iD_Usuario, Nullable<int> iD_Usuario_Accion)
        {
            var iD_DocenteParameter = iD_Docente.HasValue ?
                new ObjectParameter("ID_Docente", iD_Docente) :
                new ObjectParameter("ID_Docente", typeof(int));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var primerApellidoParameter = primerApellido != null ?
                new ObjectParameter("PrimerApellido", primerApellido) :
                new ObjectParameter("PrimerApellido", typeof(string));
    
            var segundoApellidoParameter = segundoApellido != null ?
                new ObjectParameter("SegundoApellido", segundoApellido) :
                new ObjectParameter("SegundoApellido", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(System.DateTime));
    
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(bool));
    
            var iD_UsuarioParameter = iD_Usuario.HasValue ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(int));
    
            var iD_Usuario_AccionParameter = iD_Usuario_Accion.HasValue ?
                new ObjectParameter("ID_Usuario_Accion", iD_Usuario_Accion) :
                new ObjectParameter("ID_Usuario_Accion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditarDocente", iD_DocenteParameter, cedulaParameter, nombreParameter, primerApellidoParameter, segundoApellidoParameter, fechaNacimientoParameter, rolUsuarioParameter, activoParameter, iD_UsuarioParameter, iD_Usuario_AccionParameter);
        }
    
        public virtual int EditarEstadoAsistencia(Nullable<int> iD_Estado, string nombreEstado, Nullable<int> iD_Usuario, Nullable<int> rolUsuario, Nullable<bool> activo)
        {
            var iD_EstadoParameter = iD_Estado.HasValue ?
                new ObjectParameter("ID_Estado", iD_Estado) :
                new ObjectParameter("ID_Estado", typeof(int));
    
            var nombreEstadoParameter = nombreEstado != null ?
                new ObjectParameter("NombreEstado", nombreEstado) :
                new ObjectParameter("NombreEstado", typeof(string));
    
            var iD_UsuarioParameter = iD_Usuario.HasValue ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(int));
    
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditarEstadoAsistencia", iD_EstadoParameter, nombreEstadoParameter, iD_UsuarioParameter, rolUsuarioParameter, activoParameter);
        }
    
        public virtual int EditarEstudiante(Nullable<int> iD_Estudiante, string cedula, string nombre, string primerApellido, string segundoApellido, Nullable<System.DateTime> fechaNacimiento, Nullable<int> rolUsuario, Nullable<bool> activo, Nullable<int> iD_Usuario, Nullable<int> iD_Usuario_Accion)
        {
            var iD_EstudianteParameter = iD_Estudiante.HasValue ?
                new ObjectParameter("ID_Estudiante", iD_Estudiante) :
                new ObjectParameter("ID_Estudiante", typeof(int));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var primerApellidoParameter = primerApellido != null ?
                new ObjectParameter("PrimerApellido", primerApellido) :
                new ObjectParameter("PrimerApellido", typeof(string));
    
            var segundoApellidoParameter = segundoApellido != null ?
                new ObjectParameter("SegundoApellido", segundoApellido) :
                new ObjectParameter("SegundoApellido", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(System.DateTime));
    
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(bool));
    
            var iD_UsuarioParameter = iD_Usuario.HasValue ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(int));
    
            var iD_Usuario_AccionParameter = iD_Usuario_Accion.HasValue ?
                new ObjectParameter("ID_Usuario_Accion", iD_Usuario_Accion) :
                new ObjectParameter("ID_Usuario_Accion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditarEstudiante", iD_EstudianteParameter, cedulaParameter, nombreParameter, primerApellidoParameter, segundoApellidoParameter, fechaNacimientoParameter, rolUsuarioParameter, activoParameter, iD_UsuarioParameter, iD_Usuario_AccionParameter);
        }
    
        public virtual int EditarPadre(Nullable<int> iD_Padre, string nombre, string primerApellido, string segundoApellido, Nullable<int> rolUsuario, string email, string numero, Nullable<int> iD_Usuario_Accion)
        {
            var iD_PadreParameter = iD_Padre.HasValue ?
                new ObjectParameter("ID_Padre", iD_Padre) :
                new ObjectParameter("ID_Padre", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var primerApellidoParameter = primerApellido != null ?
                new ObjectParameter("PrimerApellido", primerApellido) :
                new ObjectParameter("PrimerApellido", typeof(string));
    
            var segundoApellidoParameter = segundoApellido != null ?
                new ObjectParameter("SegundoApellido", segundoApellido) :
                new ObjectParameter("SegundoApellido", typeof(string));
    
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var numeroParameter = numero != null ?
                new ObjectParameter("Numero", numero) :
                new ObjectParameter("Numero", typeof(string));
    
            var iD_Usuario_AccionParameter = iD_Usuario_Accion.HasValue ?
                new ObjectParameter("ID_Usuario_Accion", iD_Usuario_Accion) :
                new ObjectParameter("ID_Usuario_Accion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditarPadre", iD_PadreParameter, nombreParameter, primerApellidoParameter, segundoApellidoParameter, rolUsuarioParameter, emailParameter, numeroParameter, iD_Usuario_AccionParameter);
        }
    
        public virtual int EditarUsuario(Nullable<int> iD_Usuario, string nombre_Usuario, Nullable<int> iD_Rol, string email, Nullable<int> rolUsuario, Nullable<bool> activo, Nullable<int> iD_Usuario_Accion)
        {
            var iD_UsuarioParameter = iD_Usuario.HasValue ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(int));
    
            var nombre_UsuarioParameter = nombre_Usuario != null ?
                new ObjectParameter("Nombre_Usuario", nombre_Usuario) :
                new ObjectParameter("Nombre_Usuario", typeof(string));
    
            var iD_RolParameter = iD_Rol.HasValue ?
                new ObjectParameter("ID_Rol", iD_Rol) :
                new ObjectParameter("ID_Rol", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(bool));
    
            var iD_Usuario_AccionParameter = iD_Usuario_Accion.HasValue ?
                new ObjectParameter("ID_Usuario_Accion", iD_Usuario_Accion) :
                new ObjectParameter("ID_Usuario_Accion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditarUsuario", iD_UsuarioParameter, nombre_UsuarioParameter, iD_RolParameter, emailParameter, rolUsuarioParameter, activoParameter, iD_Usuario_AccionParameter);
        }
    
        public virtual int EliminarPadre(Nullable<int> iD_Padre, Nullable<int> rolUsuario, Nullable<int> iD_Usuario_Accion)
        {
            var iD_PadreParameter = iD_Padre.HasValue ?
                new ObjectParameter("ID_Padre", iD_Padre) :
                new ObjectParameter("ID_Padre", typeof(int));
    
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            var iD_Usuario_AccionParameter = iD_Usuario_Accion.HasValue ?
                new ObjectParameter("ID_Usuario_Accion", iD_Usuario_Accion) :
                new ObjectParameter("ID_Usuario_Accion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarPadre", iD_PadreParameter, rolUsuarioParameter, iD_Usuario_AccionParameter);
        }
    
        public virtual int GenerarContrasennaAleatoria(ObjectParameter contrasenna)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GenerarContrasennaAleatoria", contrasenna);
        }
    
        public virtual int GenerarSalt(ObjectParameter salt)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GenerarSalt", salt);
        }
    
        public virtual ObjectResult<string> GenerarToken(Nullable<int> iD_Usuario)
        {
            var iD_UsuarioParameter = iD_Usuario.HasValue ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GenerarToken", iD_UsuarioParameter);
        }
    
        public virtual ObjectResult<IniciarSesion_Result> IniciarSesion(string nombre_Usuario, string contrasenna)
        {
            var nombre_UsuarioParameter = nombre_Usuario != null ?
                new ObjectParameter("Nombre_Usuario", nombre_Usuario) :
                new ObjectParameter("Nombre_Usuario", typeof(string));
    
            var contrasennaParameter = contrasenna != null ?
                new ObjectParameter("Contrasenna", contrasenna) :
                new ObjectParameter("Contrasenna", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IniciarSesion_Result>("IniciarSesion", nombre_UsuarioParameter, contrasennaParameter);
        }
    
        public virtual int LimpiarTokensExpirados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LimpiarTokensExpirados");
        }
    
        public virtual ObjectResult<ListarEstudiantesEnTablaAsistencia_Result> ListarEstudiantesEnTablaAsistencia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarEstudiantesEnTablaAsistencia_Result>("ListarEstudiantesEnTablaAsistencia");
        }
    
        public virtual ObjectResult<ObtenerAsistenciaClasePorFechas_Result> ObtenerAsistenciaClasePorFechas(Nullable<int> rolUsuario, Nullable<int> idClase, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("rolUsuario", rolUsuario) :
                new ObjectParameter("rolUsuario", typeof(int));
    
            var idClaseParameter = idClase.HasValue ?
                new ObjectParameter("idClase", idClase) :
                new ObjectParameter("idClase", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerAsistenciaClasePorFechas_Result>("ObtenerAsistenciaClasePorFechas", rolUsuarioParameter, idClaseParameter, fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<ObtenerAsistenciaEstudiantePorFechas_Result> ObtenerAsistenciaEstudiantePorFechas(Nullable<int> rolUsuario, Nullable<int> idEstudiante, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("rolUsuario", rolUsuario) :
                new ObjectParameter("rolUsuario", typeof(int));
    
            var idEstudianteParameter = idEstudiante.HasValue ?
                new ObjectParameter("idEstudiante", idEstudiante) :
                new ObjectParameter("idEstudiante", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerAsistenciaEstudiantePorFechas_Result>("ObtenerAsistenciaEstudiantePorFechas", rolUsuarioParameter, idEstudianteParameter, fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<ObtenerAsistenciaGradoPorFechas_Result> ObtenerAsistenciaGradoPorFechas(Nullable<int> rolUsuario, Nullable<int> idGrado, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("rolUsuario", rolUsuario) :
                new ObjectParameter("rolUsuario", typeof(int));
    
            var idGradoParameter = idGrado.HasValue ?
                new ObjectParameter("idGrado", idGrado) :
                new ObjectParameter("idGrado", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerAsistenciaGradoPorFechas_Result>("ObtenerAsistenciaGradoPorFechas", rolUsuarioParameter, idGradoParameter, fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<ObtenerCalificacionesEstudiantePorFechas_Result> ObtenerCalificacionesEstudiantePorFechas(Nullable<int> rolUsuario, Nullable<int> idEstudiante, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("rolUsuario", rolUsuario) :
                new ObjectParameter("rolUsuario", typeof(int));
    
            var idEstudianteParameter = idEstudiante.HasValue ?
                new ObjectParameter("idEstudiante", idEstudiante) :
                new ObjectParameter("idEstudiante", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerCalificacionesEstudiantePorFechas_Result>("ObtenerCalificacionesEstudiantePorFechas", rolUsuarioParameter, idEstudianteParameter, fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<ObtenerClasesConAsistencia_Result> ObtenerClasesConAsistencia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerClasesConAsistencia_Result>("ObtenerClasesConAsistencia");
        }
    
        public virtual ObjectResult<ObtenerEstudiantesConAsistencia_Result> ObtenerEstudiantesConAsistencia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerEstudiantesConAsistencia_Result>("ObtenerEstudiantesConAsistencia");
        }
    
        public virtual ObjectResult<ObtenerEstudiantesConCalificaciones_Result> ObtenerEstudiantesConCalificaciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerEstudiantesConCalificaciones_Result>("ObtenerEstudiantesConCalificaciones");
        }
    
        public virtual ObjectResult<ObtenerGradosConAsistencia_Result> ObtenerGradosConAsistencia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerGradosConAsistencia_Result>("ObtenerGradosConAsistencia");
        }
    
        public virtual ObjectResult<ObtenerUsuariosNoAsignados_Result> ObtenerUsuariosNoAsignados(Nullable<int> rolUsuario)
        {
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerUsuariosNoAsignados_Result>("ObtenerUsuariosNoAsignados", rolUsuarioParameter);
        }
    
        public virtual ObjectResult<Tokens> RecuperarContrasennaPaso1(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tokens>("RecuperarContrasennaPaso1", emailParameter);
        }
    
        public virtual ObjectResult<Tokens> RecuperarContrasennaPaso1(string email, MergeOption mergeOption)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tokens>("RecuperarContrasennaPaso1", mergeOption, emailParameter);
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> RecuperarContrasennaPaso2(string email, string token, string nuevaContrasenna)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(string));
    
            var nuevaContrasennaParameter = nuevaContrasenna != null ?
                new ObjectParameter("NuevaContrasenna", nuevaContrasenna) :
                new ObjectParameter("NuevaContrasenna", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("RecuperarContrasennaPaso2", emailParameter, tokenParameter, nuevaContrasennaParameter);
        }
    
        public virtual ObjectResult<VerAsistencia_Result> VerAsistencia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerAsistencia_Result>("VerAsistencia");
        }
    
        public virtual ObjectResult<VerAsistenciaPorGrado_Result> VerAsistenciaPorGrado(Nullable<int> iD_Grado)
        {
            var iD_GradoParameter = iD_Grado.HasValue ?
                new ObjectParameter("ID_Grado", iD_Grado) :
                new ObjectParameter("ID_Grado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerAsistenciaPorGrado_Result>("VerAsistenciaPorGrado", iD_GradoParameter);
        }
    
        public virtual ObjectResult<VerAsistenciaPorIdEstudiante_Result> VerAsistenciaPorIdEstudiante(Nullable<int> iD_Estudiante)
        {
            var iD_EstudianteParameter = iD_Estudiante.HasValue ?
                new ObjectParameter("ID_Estudiante", iD_Estudiante) :
                new ObjectParameter("ID_Estudiante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerAsistenciaPorIdEstudiante_Result>("VerAsistenciaPorIdEstudiante", iD_EstudianteParameter);
        }
    
        public virtual ObjectResult<VerAsistenciaPorPerioddo_Result> VerAsistenciaPorPerioddo(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerAsistenciaPorPerioddo_Result>("VerAsistenciaPorPerioddo", fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<VerAuditoriaAdministracion_Result> VerAuditoriaAdministracion(Nullable<int> rolUsuario)
        {
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerAuditoriaAdministracion_Result>("VerAuditoriaAdministracion", rolUsuarioParameter);
        }
    
        public virtual ObjectResult<VerAuditoriaAsistencia_Result> VerAuditoriaAsistencia(Nullable<int> rolUsuario)
        {
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerAuditoriaAsistencia_Result>("VerAuditoriaAsistencia", rolUsuarioParameter);
        }
    
        public virtual ObjectResult<VerAuditoriaAvisosGenerales_Result> VerAuditoriaAvisosGenerales(Nullable<int> rolUsuario)
        {
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerAuditoriaAvisosGenerales_Result>("VerAuditoriaAvisosGenerales", rolUsuarioParameter);
        }
    
        public virtual ObjectResult<VerAuditoriaCalificaciones_Result> VerAuditoriaCalificaciones(Nullable<int> rolUsuario)
        {
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerAuditoriaCalificaciones_Result>("VerAuditoriaCalificaciones", rolUsuarioParameter);
        }
    
        public virtual ObjectResult<VerAuditoriaClases_Result> VerAuditoriaClases(Nullable<int> rolUsuario)
        {
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerAuditoriaClases_Result>("VerAuditoriaClases", rolUsuarioParameter);
        }
    
        public virtual ObjectResult<VerAuditoriaDocentes_Result> VerAuditoriaDocentes(Nullable<int> rolUsuario)
        {
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerAuditoriaDocentes_Result>("VerAuditoriaDocentes", rolUsuarioParameter);
        }
    
        public virtual ObjectResult<VerAuditoriaEstudiantes_Result> VerAuditoriaEstudiantes(Nullable<int> rolUsuario)
        {
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerAuditoriaEstudiantes_Result>("VerAuditoriaEstudiantes", rolUsuarioParameter);
        }
    
        public virtual ObjectResult<VerAuditoriaIniciosSesion_Result> VerAuditoriaIniciosSesion(Nullable<int> rolUsuario)
        {
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerAuditoriaIniciosSesion_Result>("VerAuditoriaIniciosSesion", rolUsuarioParameter);
        }
    
        public virtual ObjectResult<VerAvisoGeneral_Result> VerAvisoGeneral(Nullable<int> iD_AvisoGeneral)
        {
            var iD_AvisoGeneralParameter = iD_AvisoGeneral.HasValue ?
                new ObjectParameter("ID_AvisoGeneral", iD_AvisoGeneral) :
                new ObjectParameter("ID_AvisoGeneral", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerAvisoGeneral_Result>("VerAvisoGeneral", iD_AvisoGeneralParameter);
        }
    
        public virtual ObjectResult<VerAvisosGenerales_Result> VerAvisosGenerales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerAvisosGenerales_Result>("VerAvisosGenerales");
        }
    
        public virtual ObjectResult<VerCalificaciones_Result> VerCalificaciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerCalificaciones_Result>("VerCalificaciones");
        }
    
        public virtual ObjectResult<VerCalificacionesPorID_Result> VerCalificacionesPorID(Nullable<int> iD_Estudiante)
        {
            var iD_EstudianteParameter = iD_Estudiante.HasValue ?
                new ObjectParameter("ID_Estudiante", iD_Estudiante) :
                new ObjectParameter("ID_Estudiante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerCalificacionesPorID_Result>("VerCalificacionesPorID", iD_EstudianteParameter);
        }
    
        public virtual ObjectResult<VerClasePorID_Result> VerClasePorID(Nullable<int> iD_Clase)
        {
            var iD_ClaseParameter = iD_Clase.HasValue ?
                new ObjectParameter("ID_Clase", iD_Clase) :
                new ObjectParameter("ID_Clase", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerClasePorID_Result>("VerClasePorID", iD_ClaseParameter);
        }
    
        public virtual ObjectResult<VerClases_Result> VerClases()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerClases_Result>("VerClases");
        }
    
        public virtual ObjectResult<VerDocentes_Result> VerDocentes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerDocentes_Result>("VerDocentes");
        }
    
        public virtual ObjectResult<VerDocentesClases_Result> VerDocentesClases()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerDocentesClases_Result>("VerDocentesClases");
        }
    
        public virtual ObjectResult<VerEstadoAsistenciaPorID_Result> VerEstadoAsistenciaPorID(Nullable<int> iD_Estado)
        {
            var iD_EstadoParameter = iD_Estado.HasValue ?
                new ObjectParameter("ID_Estado", iD_Estado) :
                new ObjectParameter("ID_Estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerEstadoAsistenciaPorID_Result>("VerEstadoAsistenciaPorID", iD_EstadoParameter);
        }
    
        public virtual ObjectResult<VerEstadosAsistencia_Result> VerEstadosAsistencia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerEstadosAsistencia_Result>("VerEstadosAsistencia");
        }
    
        public virtual ObjectResult<VerEstudiantes_Result> VerEstudiantes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerEstudiantes_Result>("VerEstudiantes");
        }
    
        public virtual ObjectResult<VerEstudiantesGrados_Result> VerEstudiantesGrados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerEstudiantesGrados_Result>("VerEstudiantesGrados");
        }
    
        public virtual ObjectResult<VerEstudiantesPadres_Result> VerEstudiantesPadres()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerEstudiantesPadres_Result>("VerEstudiantesPadres");
        }
    
        public virtual ObjectResult<VerPadres_Result> VerPadres()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerPadres_Result>("VerPadres");
        }
    
        public virtual ObjectResult<VerPerfilDeAdministrador_Result> VerPerfilDeAdministrador(Nullable<int> iD_Usuario)
        {
            var iD_UsuarioParameter = iD_Usuario.HasValue ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerPerfilDeAdministrador_Result>("VerPerfilDeAdministrador", iD_UsuarioParameter);
        }
    
        public virtual ObjectResult<VerPerfilDeDocente_Result> VerPerfilDeDocente(Nullable<int> iD_Usuario)
        {
            var iD_UsuarioParameter = iD_Usuario.HasValue ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerPerfilDeDocente_Result>("VerPerfilDeDocente", iD_UsuarioParameter);
        }
    
        public virtual ObjectResult<VerPerfilDeEstudiante_Result> VerPerfilDeEstudiante(Nullable<int> iD_Usuario)
        {
            var iD_UsuarioParameter = iD_Usuario.HasValue ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerPerfilDeEstudiante_Result>("VerPerfilDeEstudiante", iD_UsuarioParameter);
        }
    
        public virtual ObjectResult<VerRoles_Result> VerRoles(Nullable<int> rolUsuario)
        {
            var rolUsuarioParameter = rolUsuario.HasValue ?
                new ObjectParameter("RolUsuario", rolUsuario) :
                new ObjectParameter("RolUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerRoles_Result>("VerRoles", rolUsuarioParameter);
        }
    
        public virtual ObjectResult<VerUsuarioPorId_Result> VerUsuarioPorId(Nullable<int> iD_Usuario)
        {
            var iD_UsuarioParameter = iD_Usuario.HasValue ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerUsuarioPorId_Result>("VerUsuarioPorId", iD_UsuarioParameter);
        }
    
        public virtual ObjectResult<VerUsuarios_Result> VerUsuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerUsuarios_Result>("VerUsuarios");
        }
    }
}
