//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.AuditoriaAdministracion = new HashSet<AuditoriaAdministracion>();
            this.AuditoriaAsistencia = new HashSet<AuditoriaAsistencia>();
            this.AuditoriaAvisosGenerales = new HashSet<AuditoriaAvisosGenerales>();
            this.AuditoriaCalificaciones = new HashSet<AuditoriaCalificaciones>();
            this.AuditoriaClases = new HashSet<AuditoriaClases>();
            this.AuditoriaDocentes = new HashSet<AuditoriaDocentes>();
            this.AuditoriaEstudiantes = new HashSet<AuditoriaEstudiantes>();
            this.AuditoriaIniciosSesion = new HashSet<AuditoriaIniciosSesion>();
            this.Docentes = new HashSet<Docentes>();
            this.Estudiantes = new HashSet<Estudiantes>();
            this.IniciosSesion = new HashSet<IniciosSesion>();
            this.Mensajeria = new HashSet<Mensajeria>();
            this.Mensajeria1 = new HashSet<Mensajeria>();
            this.Tokens = new HashSet<Tokens>();
        }
    
        public int ID_Usuario { get; set; }
        public string Nombre_Usuario { get; set; }
        public string ContrasennaHash { get; set; }
        public string Salt { get; set; }
        public int ID_Rol { get; set; }
        public bool Activo { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditoriaAdministracion> AuditoriaAdministracion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditoriaAsistencia> AuditoriaAsistencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditoriaAvisosGenerales> AuditoriaAvisosGenerales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditoriaCalificaciones> AuditoriaCalificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditoriaClases> AuditoriaClases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditoriaDocentes> AuditoriaDocentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditoriaEstudiantes> AuditoriaEstudiantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditoriaIniciosSesion> AuditoriaIniciosSesion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Docentes> Docentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estudiantes> Estudiantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IniciosSesion> IniciosSesion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mensajeria> Mensajeria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mensajeria> Mensajeria1 { get; set; }
        public virtual Roles Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tokens> Tokens { get; set; }
    }
}
